name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Debug - List files
        run: |
          ls -la
          echo "Contents of index.html:"
          cat index.html | grep -A 10 "<script"

      - name: Build
        run: |
          # Add any build steps here if needed
          # For now, we're just copying static files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: .
          exclude_assets: '.github,node_modules,package.json,package-lock.json,README.md'
          force_orphan: true # Force push changes 