# DEPRECATED - Please use deploy-frontend.yml instead
# This workflow is kept for reference but is no longer used

name: Deprecated Workflow

on:
  # Prevents this workflow from running
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Info
        run: |
          echo "This workflow is deprecated. Please use deploy-frontend.yml instead." 